services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sprintify
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: sprintify
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: sprintify-app
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/sprintify
      DATABASE_USER: sprintify
      DATABASE_PASSWORD: secret
      JWT_SECRET_KEY: pezjezgjizgjizegjizeijgzegjzegpjzejpgzepjgjpgijzejpgpzgipzipegpiepgzepgjpzejvpjzdjpvvjzevzejvjpzepjvepzj
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: