DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS sprints;

-- Roles table
create table roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

-- Users table
create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    password varchar(255),
    username varchar(255),
    role_id  bigint,
    constraint FKp56c1712k691lhsyewcssf40f
        foreign key (role_id) references roles (id)
);

-- Projects table
create table projects
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    description varchar(255),
    owner_id    bigint not null,
    constraint fk_project_owner
        foreign key (owner_id) references users (id)
);

-- Sprints table
create table sprints
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255),
    project_id bigint not null,
    constraint fk_sprint_project
        foreign key (project_id) references projects (id)
);

-- Tasks table
create table tasks
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(100) not null,
    description varchar(255),
    sprint_id   bigint not null,
    due_date    date,
    status      smallint,
    title       varchar(255),
    assignee_id bigint,
    constraint UK29mywj10dui941nqk773wvuxj
        unique (assignee_id),
    constraint FKekr1dgiqktpyoip3qmp6lxsit
        foreign key (assignee_id) references users (id),
    constraint fk_task_sprint
        foreign key (sprint_id) references sprints (id)
);
