name: Generate Changelog

on:
  push:
    branches:
      - main
      - dev

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important pour git-chglog

      - name: Setup Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install git-chglog
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.15.4/git-chglog_0.15.4_linux_amd64.tar.gz
          tar -xzf git-chglog_0.15.4_linux_amd64.tar.gz
          sudo mv git-chglog /usr/local/bin/

      - name: Generate changelog
        run: git-chglog -o CHANGELOG.md

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip ci]" || echo "No changes to commit"
          git push
