name: CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # (Optionnel) run tests
      - name: Run tests
        run: |
          echo "run your tests here"
          # ex: npm ci && npm test

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nekeroo/sprintify:latest
            ghcr.io/nekeroo/sprintify:${{ github.sha }}

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deploy (API)
        run: |
          curl -fsSL \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            "$COOLIFY_DEPLOY_HOOK"